version: "3.9"
services:
  web:
    depends_on:
      - db
    build:
      dockerfile: ./Dockerfile
      context: .
    tty: true
    command: ./build/cmd/start.sh
    stdin_open: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      RAILS_ENV: development
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - bundle:/app/vendor/bundle

  db:
    image: postgres:alpine3.15
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  node_modules:
  bundle: