default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: 5
  timeout: 5000
  database: <%= ENV['RAILS_ENV'] %>_db
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
